package org.iskcon.iys.shared.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * Base entity providing:
 * <ul>
 *   <li>UUID primary key (generated by the database via gen_random_uuid())</li>
 *   <li>JPA audit fields: created_at, updated_at, created_by, updated_by</li>
 *   <li>Soft-delete fields: deleted_at, deleted_by</li>
 * </ul>
 *
 * <p>All entity classes must extend this class. Soft-delete filtering is handled
 * at the subclass level via Hibernate's {@code @SQLRestriction}.</p>
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseAuditEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * UUID of the user who created this record.
     * Populated automatically by {@link org.iskcon.iys.shared.config.JpaConfig.IysAuditorProvider}.
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false)
    private UUID createdBy;

    /**
     * UUID of the user who last modified this record.
     */
    @LastModifiedBy
    @Column(name = "updated_by")
    private UUID updatedBy;

    /**
     * When set, this record is considered soft-deleted.
     * Application queries always add {@code WHERE deleted_at IS NULL}.
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    /**
     * UUID of the user who performed the soft-delete.
     */
    @Column(name = "deleted_by")
    private UUID deletedBy;

    /** Returns {@code true} if this record has been soft-deleted. */
    @Transient
    public boolean isDeleted() {
        return deletedAt != null;
    }
}
